/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 car1.gltf --transform 
Files: car1.gltf [19.49MB] > G:\REACT PROJECTS\3D MODELS for 3d-portfolio\car__4_free_3d_model\car1-transformed.glb [1.5MB] (92%)
Author: ₦₥₵ ฿₵ (https://sketchfab.com/oxyplik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/car-4-free-3d-model-0bb02eb19b594617bf4f71d75893d52b
Title: Car # 4 Free 3D Model
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("car1-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["Material0-material-material"].geometry}
        material={materials.PaletteMaterial001}
        position={[0.284, 0.892, 0.846]}
        rotation={[-0.804, -1.565, -0.805]}
        scale={[0.322, 1.03, 1.065]}
      />
      <mesh
        geometry={nodes["Material3-material-material"].geometry}
        material={materials.PaletteMaterial002}
        position={[0.284, 0.892, 0.846]}
        rotation={[-0.804, -1.565, -0.805]}
        scale={[0.322, 1.03, 1.065]}
      />
      <mesh
        geometry={nodes["Material4-material-material"].geometry}
        material={materials["Material4-material"]}
        position={[0.284, 0.892, 0.846]}
        rotation={[-0.804, -1.565, -0.805]}
        scale={[0.322, 1.03, 1.065]}
      />
      <mesh
        geometry={nodes["Material6-material-material"].geometry}
        material={materials["Material6-material"]}
        position={[0.284, 0.892, 0.846]}
        rotation={[-0.804, -1.565, -0.805]}
        scale={[0.322, 1.03, 1.065]}
      />
      <mesh
        geometry={nodes["Material10-material-material"].geometry}
        material={materials["Material10-material"]}
        position={[-0.644, 0.898, 0.853]}
        rotation={[-0.804, -1.565, -0.805]}
        scale={[0.336, 1.033, 1.093]}
      />
      <mesh
        geometry={nodes["Material12-material-material"].geometry}
        material={materials["Material12-material"]}
        position={[-0.794, 0.727, -0.024]}
        rotation={[-0.804, -1.565, -0.805]}
        scale={[1.723, 0.81, 4.153]}
      />
      <mesh
        geometry={nodes["Material13-material-material"].geometry}
        material={materials["Material13-material"]}
        position={[-0.794, 0.727, -0.024]}
        rotation={[-0.804, -1.565, -0.805]}
        scale={[1.723, 0.81, 4.153]}
      />
      <mesh
        geometry={nodes["Material14-material-material"].geometry}
        material={materials["Material14-material"]}
        position={[-0.794, 0.727, -0.024]}
        rotation={[-0.804, -1.565, -0.805]}
        scale={[1.723, 0.81, 4.153]}
      />
      <mesh
        geometry={nodes["Material16-material-material"].geometry}
        material={materials["Material16-material"]}
        position={[-0.794, 0.727, -0.024]}
        rotation={[-0.804, -1.565, -0.805]}
        scale={[1.723, 0.81, 4.153]}
      />
      <mesh
        geometry={nodes["Material17-material-material"].geometry}
        material={materials["Material17-material"]}
        position={[1.643, 0.37, 0.685]}
        rotation={[-0.804, -1.565, -0.805]}
        scale={[0.226, 0.337, 0.366]}
      />
      <mesh
        geometry={nodes["Material20-material-material"].geometry}
        material={materials["Material20-material"]}
        position={[-0.651, 0.898, -0.902]}
        rotation={[-0.804, -1.565, -0.805]}
        scale={[0.336, 1.033, 1.093]}
      />
      <mesh
        geometry={nodes["Material23-material-material"].geometry}
        material={materials["Material23-material"]}
        position={[0.84, 0.911, -0.394]}
        rotation={[-0.804, -1.565, -0.805]}
        scale={[0.745, 0.15, 0.162]}
      />
      <mesh
        geometry={nodes["Material24-material-material"].geometry}
        material={materials["Material24-material"]}
        position={[-0.889, 0.763, -0.024]}
        rotation={[-0.804, -1.565, -0.805]}
        scale={[1.909, 0.659, 0.87]}
      />
      <mesh
        geometry={nodes["Material45-material-material"].geometry}
        material={materials["Material45-material"]}
        position={[0.277, 0.893, -0.903]}
        rotation={[-0.804, -1.565, -0.805]}
        scale={[0.322, 1.03, 1.065]}
      />
      <mesh
        geometry={nodes["Material55-material-material"].geometry}
        material={materials["Material55-material"]}
        position={[0.058, 0.714, -0.028]}
        rotation={[-0.804, -1.565, -0.805]}
        scale={[1.788, 0.673, 0.821]}
      />
      <mesh
        geometry={nodes["Material72-material-material"].geometry}
        material={materials["Material72-material"]}
        position={[-1.464, 0.372, 0.776]}
        rotation={[-1.57, 0.004, -3.138]}
        scale={[0.713, 0.266, 0.713]}
      />
      <mesh
        geometry={nodes["Material73-material-material"].geometry}
        material={materials["Material73-material"]}
        position={[-1.464, 0.372, 0.776]}
        rotation={[-1.57, 0.004, -3.138]}
        scale={[0.713, 0.266, 0.713]}
      />
    </group>
  );
}

useGLTF.preload("car1-transformed.glb");
