/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 delor.gltf --transform 
Files: delor.gltf [15.1MB] > G:\REACT PROJECTS\3D MODELS for 3d-portfolio\1981_delorean_dmc-12s\delor-transformed.glb [817.67KB] (95%)
Author: ₦₥₵ ฿₵ (https://sketchfab.com/nmcbc)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/1981-delorean-dmc-12s-7ee562c098eb47808cd3bc3f709dd047
Title: 1981 DeLorean DMC-12s
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("delor-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <lineSegments
        geometry={nodes.Material2_1.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material3.geometry}
        material={materials.PaletteMaterial002}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_2.geometry}
        material={materials.PaletteMaterial003}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material3_1.geometry}
        material={materials.PaletteMaterial004}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material3_2.geometry}
        material={materials.PaletteMaterial005}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("delor-transformed.glb");
