/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 mustang.gltf --transform 
Files: mustang.gltf [4.62MB] > G:\REACT PROJECTS\3D MODELS for 3d-portfolio\ford_mustang_boss_302\mustang-transformed.glb [360.74KB] (92%)
Author: BadKarma™ (https://sketchfab.com/890244234)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ford-mustang-boss-302-58eef4aca9bd469c826ce3d237e37046
Title: Ford Mustang Boss 302
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("mustang-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.AERIALS}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.91}
      />
      <mesh
        geometry={nodes.Object_3.geometry}
        material={materials.BODY_NUMBER_PAINT}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.91}
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.CABIN}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.91}
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.CALIPER}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.91}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.DISCS}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.91}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.LIGHTS_GLASS}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.91}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials.LIGHTS_POD}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.91}
      />
      <mesh
        geometry={nodes.Object_11.geometry}
        material={materials.MATT}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.91}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.SHINY_METAL}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.91}
      />
      <mesh
        geometry={nodes.Object_13.geometry}
        material={materials.SUSPENSION}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.91}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials.TARMAC_TYRE_TREAD}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.91}
      />
      <mesh
        geometry={nodes.Object_15.geometry}
        material={materials.TARMAC_TYRE_WALL}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.91}
      />
      <mesh
        geometry={nodes.Object_17.geometry}
        material={materials.WINDOW_GLASS}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.91}
      />
    </group>
  );
}

useGLTF.preload("mustang-transformed.glb");
