/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 retro.gltf --transform 
Files: retro.gltf [9.1MB] > G:\REACT PROJECTS\3D MODELS for 3d-portfolio\retro_van_-_free_3d_model_download\retro-transformed.glb [1.51MB] (83%)
Author: ₦ɆɄⱤØ ØӾɎ ₱Ⱡł₭ (https://sketchfab.com/oxyplik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-van-free-3d-model-download-28afdb028c4f4ef7b33dd728fc0d406a
Title: Retro Van - Free 3D Model download
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("retro-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["Material0-material-material"].geometry}
        material={materials.PaletteMaterial001}
        position={[-3.508, -0.828, -0.452]}
        rotation={[0.329, -1.568, 0.34]}
        scale={[0.306, 0.315, 0.655]}
      />
      <mesh
        geometry={nodes["Material2-material-material"].geometry}
        material={materials.PaletteMaterial002}
        position={[-1.704, 0.722, -0.835]}
        rotation={[0.329, -1.568, 0.34]}
        scale={[0.317, 0.64, 3.997]}
      />
      <mesh
        geometry={nodes["Material20-material-material"].geometry}
        material={materials["Material30-material"]}
        position={[-1.24, 0.186, 0.001]}
        rotation={[0.33, -1.568, 0.341]}
        scale={[2.094, 1.954, 5.073]}
      />
      <mesh
        geometry={nodes["Material74-material-material"].geometry}
        material={materials["Material74-material"]}
        position={[0.162, -0.65, 0.857]}
        rotation={[-1.582, -0.001, 0.002]}
        scale={[0.725, 0.332, 0.725]}
      />
      <mesh
        geometry={nodes["Material75-material-material"].geometry}
        material={materials["Material75-material"]}
        position={[0.162, -0.65, 0.857]}
        rotation={[-1.582, -0.001, 0.002]}
        scale={[0.725, 0.332, 0.725]}
      />
      <mesh
        geometry={nodes["Material76-material-material"].geometry}
        material={materials["Material76-material"]}
        position={[0.162, -0.65, 0.857]}
        rotation={[-1.582, -0.001, 0.002]}
        scale={[0.725, 0.332, 0.725]}
      />
      <mesh
        geometry={nodes["Material77-material-material"].geometry}
        material={materials["Material77-material"]}
        position={[0.162, -0.65, 0.857]}
        rotation={[-1.582, -0.001, 0.002]}
        scale={[0.725, 0.332, 0.725]}
      />
      <mesh
        geometry={nodes["Material78-material-material"].geometry}
        material={materials["Material78-material"]}
        position={[0.162, -0.65, 0.857]}
        rotation={[-1.582, -0.001, 0.002]}
        scale={[0.725, 0.332, 0.725]}
      />
      <mesh
        geometry={nodes["Material85-material-material"].geometry}
        material={materials["Material85-material"]}
        position={[-1.47, 1.161, -0.021]}
        rotation={[0.329, -1.568, 0.34]}
        scale={[1.786, 0.545, 3.783]}
      />
    </group>
  );
}

useGLTF.preload("retro-transformed.glb");
